name: HackerNews

on:
  schedule:
    - cron: '0 10,22 * * *' # JST 7:00 & 19:00
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - env:
          PIP_REQUIRE_VIRTUALENV: false
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install haxor
          python -m script
